#!/bin/sh

error () {
	echo "$1" >&2
	exit 1
}

BINDIR="$( dirname "$0" )"
DATADIR="$1"
[ -d "$DATADIR" ] || error "Invalid argument: $DATADIR is not a data dir."

mkdir -p "$DATADIR"/tmp
cut -d: -f2- "$DATADIR"/crldps.csv | sort -u | tr -d '"' | grep http | while read url; do
    CRL_FILE="$DATADIR/tmp/$( echo $url | tr / + )"
    curl $url > "$CRL_FILE";
    "$BINDIR"/inject -t crls -d "$DATADIR" "$CRL_FILE"
    rm -f "$CRL_FILE"
done
rmdir "$DATADIR"/tmp
